example:
  property: '[GitHub] licensing-service-prod.yml: PROD'

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/prod?currentSchema=licensing
    username: prod
    password: postgres