example:
  property: '[classpath:] licensing-service-dev.yml: DEV'

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/dev?currentSchema=licensing
    username: dev
    password: postgres
