example:
  property: '[GitHub] organization-service-dev.yml: DEV'

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/dev?currentSchema=organization
    username: dev
    password: {cipher}928fd0b91c2e3acda9131c6d5c633ecc94d911c7802439984793d0f33490fdd1