example:
  property: '[GitHub] organization-service-prod.yml: PROD'

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/prod?currentSchema=organization
    username: prod
    password: {cipher}928fd0b91c2e3acda9131c6d5c633ecc94d911c7802439984793d0f33490fdd1