example:
  property: '[GitHub] organization-service-prod.yml: PROD'

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/prod?currentSchema=organization
    username: prod
    password: postgres