example:
  property: '[GitHub] organization-service-dev.yml: DEV'

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/dev?currentSchema=organization
    username: dev
    password: postgres